### ISSUE TITLE
Firebase Analytics Issue

### ISSUE THREAD

**Issue by BenQ12345** [myflashlab/Firebase-ANE#243] opened 2018-09-14 07:53 UTC
Hi,
   I am using Demo MainAnalytics.as file there are two buttons like **Log event And get app instance id** 
if i click **log event button** there is no reaction from  firebase console and Events also not showing in firebase console.

Please suggest me solution for it.

**Comment by myflashlab** [comment] 2018-09-14 14:34
it usually takes a few hours if you have created your Firebase app recently. If not, it takes a few minutes to see the logs on the console. Are you sure you are looking at the correct place in your Firebase console?

<img width="589" alt="screen shot 2018-09-14 at 6 33 26 pm" src="https://user-images.githubusercontent.com/1692948/45556620-c19b3600-b84c-11e8-9086-175aed6cde3b.png">

**Comment by nikhilreddy123456** [comment] 2018-09-18 04:30
Hi, everything is fine but it not showing Event in firebase console. I am developing in Animated CC so want to add coding to display in console.

init()
function init():void
		{
			//OverrideAir.enableDebugger(myDebuggerDelegate);
			
			var isConfigFound:Boolean = Firebase.init();
			
			if (isConfigFound)
			{
				var config:FirebaseConfig = Firebase.getConfig();
				C.log("default_web_client_id = " + 			config.default_web_client_id);
				C.log("firebase_database_url = " + 			config.firebase_database_url);
				C.log("gcm_defaultSenderId = " + 			config.gcm_defaultSenderId);
				C.log("google_api_key = " + 				config.google_api_key);
				C.log("google_app_id = " + 					config.google_app_id);
				C.log("google_crash_reporting_api_key = " + config.google_crash_reporting_api_key);
				C.log("google_storage_bucket = " + 			config.google_storage_bucket);
				C.log("project_id = " /*+ 					config.project_id*/);
				
				initFirebaseAnalytics();
			}
			else
			{
				C.log("Config file is not found!");
			}
		}
		
		 function initFirebaseAnalytics():void
		{
			FirebaseAnalytics.init();
			
			var btn1:MySprite = createBtn("Log event");
			btn1.addEventListener(MouseEvent.CLICK, logEvent);
			_list.add(btn1);
			
			function logEvent(e:MouseEvent):void
			{
				C.log("send logEvent");
				
				var bundle:AnalyticsParam = new AnalyticsParam();
				bundle.addString(AnalyticsParam.ITEM_ID, "yourContentId");
				bundle.addString(AnalyticsParam.ITEM_NAME, "yourContentName");
				bundle.addString(AnalyticsParam.CONTENT_TYPE, "image");
				
				FirebaseAnalytics.logEvent(AnalyticsEvent.SELECT_CONTENT, bundle);
			}
			
			var btn2:MySprite = createBtn("get app instance ID");
			btn2.addEventListener(MouseEvent.CLICK, getAppInstanceID);
			_list.add(btn2);
			
			function getAppInstanceID(e:MouseEvent):void
			{
				C.log("AppInstanceID = ");
				FirebaseAnalytics.getAppInstanceID(onResult);
				C.log("AppInstanceID = ");
			}
			
			function onResult($id:String):void
			{
				C.log("nikhil = ");
				C.log("AppInstanceID = " + $id);
			}
		}

**Comment by nikhilreddy123456** [comment] 2018-09-19 05:56
import com.myflashlab.air.extensions.firebase.core.*;
import com.myflashlab.air.extensions.firebase.analytics.*;
import com.myflashlab.air.extensions.dependency.OverrideAir;

Start();
function Start():void
{
	try
	{
		var isConfigFound:Boolean = Firebase.init();
	}
	catch (e:Error)
	{
		notify( e+"");
	}

	if (isConfigFound)
	{
		var config:FirebaseConfig = Firebase.getConfig();
		config.projectID="mysteries-of-circle-world-2";
		notify("default_web_client_id = " + 			config.default_web_client_id);
		notify("firebase_database_url = " + 			config.firebase_database_url);
		notify("gcm_defaultSenderId = " + 			config.gcm_defaultSenderId);
		notify("google_api_key = " + 				config.google_api_key);
		notify("google_app_id = " + 					config.google_app_id);
		notify("google_crash_reporting_api_key = " + config.google_crash_reporting_api_key);
		notify("google_storage_bucket = " + 			config.google_storage_bucket);
		notify("project_id = " + 					config.projectID);
		
		// You must initialize any of the other Firebase children after a successful initialization
		// of the Core ANE.
		initFirebaseAnalytics();
	}
	else
	{
		notify("Config file is not found!");
	}
}

function initFirebaseAnalytics():void
{
	FirebaseAnalytics.init();
	FirebaseAnalytics.analyticsCollectionEnabled = true;
	notify("initFirebaseAnalytics");
	notify("EXTENSION_ID="+FirebaseAnalytics.EXTENSION_ID);
	readyToUseFirebase();
}

function notify( str:String ):void
{
	_text.appendText(str+"\n");
}

function readyToUseFirebase():void
{
	Firebase.iid.addEventListener(FirebaseEvents.IID_TOKEN, onIdTokenReceived);
	Firebase.iid.addEventListener(FirebaseEvents.IID_ID, onIdReceived);
	Firebase.iid.addEventListener(FirebaseEvents.IID_TOKEN_REFRESH, onIdTokenRefresh);
}

btn1.addEventListener(MouseEvent.CLICK, getToken);
function getToken(e:MouseEvent):void
{
	Firebase.iid.getToken();
}

btn2.addEventListener(MouseEvent.CLICK, getId);
function getId(e:MouseEvent):void
{
	Firebase.iid.getID();
}

btn3.addEventListener(MouseEvent.CLICK, deliid);
function deliid(e:MouseEvent):void
{
	Firebase.iid.deleteIID();
}

function onIdTokenReceived(e:FirebaseEvents):void
{
	notify("iidToken = "+e.iidToken);
}

function onIdReceived(e:FirebaseEvents):void
{
	notify("iid id = "+e.iidID);
}

function onIdTokenRefresh(e:FirebaseEvents):void
{
	notify(">>>>> onIdTokenRefresh");
	Firebase.iid.getToken();
}		
	
abtn1.addEventListener(MouseEvent.CLICK, logEvent);
function logEvent(e:MouseEvent):void
{
	notify("send logEvent");
	
	var params:AnalyticsParam = new AnalyticsParam();
	params.addString(AnalyticsParam.ITEM_ID, "coin100");
	params.addString(AnalyticsParam.ITEM_NAME, "Coins");
	params.addString(AnalyticsParam.CONTENT_TYPE, "Purchase");
	FirebaseAnalytics.logEvent(AnalyticsEvent.SELECT_CONTENT, params);
	notify("sent logEvent");
}

abtn2.addEventListener(MouseEvent.CLICK, getAppInstanceID);
function getAppInstanceID(e:MouseEvent):void
{
	FirebaseAnalytics.getAppInstanceID(onResult);
}

function onResult($id:String):void
{
	notify("AppInstanceID = " + $id);
}

**Comment by Gokul617** [comment] 2018-09-20 05:31
I too have this same issue mentioned by #nikhilreddy123456.

**Waiting for your reply ASAP**

**Comment by myflashlab** [comment] 2018-09-20 06:14
Although don't see a reason why you're not seeing the events at your console and everything looks just fine when we test it, we have been working on V7.0.0 of Firebase ANEs for the past last month. it is already completed and we will be releasing new versions of ANEs in a few days. So, hold on there while we are preparing for the release.

**Comment by Gokulv617** [comment] 2018-09-20 06:31
Its good to hear that you are releasing a new version. may i know when it will be released ?

**Comment by deesnay** [comment] 2018-09-20 15:45
Hi, we also have a similar problem. We have a test app including the full ANE (not demo version).
The app_remove event is the only one that appears in the Firebase console (when we uninstall the app), which means that the app is still properly linked to the Firebase account somehow.
The logs in the FlashBuilder debugger look normal.
We double-checked the manifest (maybe we still missed something?).
We'll try version 7.0.0 as soon as it's released.
If you have any suggestion in between...

**Comment by myflashlab** [comment] 2018-09-21 07:15
Ok, this is weird that users are reporting analytics not working all the sudden! maybe Google has prevented new users from using older SDK version but older users are fine... maybe, just a guess :thinking: Anyhow, don't worry guys, V7.0.0 of Firebase is on it's way. it will be released this month, before September ends. Not only Firebase, but also all the dependencies and all other ANEs will be updated to include new features and bug fixes... just hold on while we're working on the ANEs. Thanks.

**Comment by deesnay** [comment] 2018-09-21 09:52
Thank you very much for your feedback. It seems we finally got it working, and we still had some parts missing in our manifest.
The truth is, there seems to be some latency between actions and the feedback we get in the Firebase console (even in the StreamView), which makes debugging a bit tricky. Ironically, it seems that uninstalling the app forces event collection (which happens otherwise every hour, as far as I understand).

**Comment by nikhilreddy123456** [comment] 2018-12-06 12:42
Hi, I am using  Firebase core and Analytics if i call the **var isConfigFound:Boolean = Firebase.init();** when i click power button and open the app again getting freeze. if i remove Firebase.init() it is working fine when i click power button off and on. what will be the issue for this scenario. please send the reply asap.

**Comment by nikhilreddy123456** [comment] 2018-12-06 12:45
Hi, I am using  Firebase core and Analytics if i call the **var isConfigFound:Boolean = Firebase.init();** when i enter the app it is working fine if i click power button and open the app again getting freeze. if i remove Firebase.init() it is working fine. what will be the issue for this scenario. please send the reply asap.

**Comment by myflashlab** [comment] 2018-12-07 03:52
@nikhilreddy123456 please send us Logcat logs if the problem is on Android or send us xcode logs if you are on iOS. In the logs, the reason of freeze/crash must be written.

**Comment by myflashlab** [comment] 2018-12-14 14:15
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).

**Closed by myflashlab** 2018-12-14 14:15 UTC
