### ISSUE TITLE
FCM iOS complete

### ISSUE THREAD

**Issue by ikuprin** [myflashlab/Firebase-ANE#218] opened 2018-06-01 12:56 UTC
If I tap on FCM message at android and application starts - FCM dashboard show me that message "completed". At iOS it is not works - no "completes".

**Comment by myflashlab** [comment] 2018-06-10 12:31
Can you please provide more information? When setting up FCM for the first time for an application it may take a few hours for it to work.

**Comment by ikuprin** [comment] 2018-06-11 12:37
Hum... Looks like not works at all.

AIR SDK 30
Firebase 4.11.0
iOS 11.3.x
iPhone 5s, iPad Air 2, iPhone 6, iPhone X.

Manifest in attach:
[manifest.txt](https://github.com/myflashlab/Firebase-ANE/files/2089937/manifest.txt)

code:
```package engine.mobile {
  
  import com.myflashlab.air.extensions.firebase.core.Firebase;
  import com.myflashlab.air.extensions.firebase.fcm.FCM;
  import com.myflashlab.air.extensions.firebase.fcm.FcmEvents;
  
  import engine.classes.*;
  import engine.debug.Debug;
  import engine.social.SocialNetwork;
  import engine.social.SocialNetworkEvents;
  
  import model.common.Settings;
  
  import model.common.SettingsMobile;
  
  public class MobilePushExtended {
    
    private var _initialized:Boolean = false;
    
    public var onTokenRefreshCallback:Function;
    public var onMessageCallback:Function;
    
    private static var _instance:MobilePushExtended;
    
    public static function getInstance():MobilePushExtended {
      _instance = _instance || new MobilePushExtended();
      return _instance;
    }
    
    public function MobilePushExtended() {
      if (Settings.STANDALONE || CapabilitiesFW.isAmazon()) {
        Debug.log("FCM is not supported on this platform (not android or ios!)");
        return;
      }
      if (Firebase.os == Firebase.ANDROID)  {
        Firebase.checkGoogleAvailability(onCheckResult);
      } else {
        onCheckResult(Firebase.SUCCESS);
      }
    }
    
    private function onCheckResult(result:int):void {
      switch(result) {
        case Firebase.SUCCESS:
          Debug.log("MobilePushExtended::checkGoogleAvailability result = SUCCESS");
          initFCM();
          _initialized = true;
          break;
        case Firebase.SERVICE_MISSING:
          Debug.error("MobilePushExtended::checkGoogleAvailability result = SERVICE_MISSING");
          break;
        case Firebase.SERVICE_VERSION_UPDATE_REQUIRED:
          Debug.error("MobilePushExtended::checkGoogleAvailability result = SERVICE_VERSION_UPDATE_REQUIRED");
          break;
        case Firebase.SERVICE_UPDATING:
          Debug.error("MobilePushExtended::checkGoogleAvailability result = SERVICE_UPDATING");
          break;
        case Firebase.SERVICE_DISABLED:
          Debug.error("MobilePushExtended::checkGoogleAvailability result = SERVICE_DISABLED");
          break;
        case Firebase.SERVICE_INVALID:
          Debug.error("MobilePushExtended::checkGoogleAvailability result = SERVICE_INVALID");
          break;
      }
    }
    
    private function initFCM():void {
      try {
        FCM.init();
        FCM.listener.addEventListener(FcmEvents.TOKEN_REFRESH, onTokenRefresh);
        FCM.listener.addEventListener(FcmEvents.MESSAGE, onMessage);
        Debug.log("FCM Token is " + FCM.getToken());
      } catch (e:Error) {
        Debug.error("MobilePushExtended::initFCM error: " + e.message);
      }
    }
    
    public function isEnabled():Boolean {
      return _initialized;
    }
    
    public function get token():String {
      if (!_initialized) {
        return null;
      }
      return FCM.getToken();
    }
    
    public function unsubscribeFromTopic(topicName:String):void {
      if (!_initialized) {
        return;
      }
      FCM.unsubscribeFromTopic(topicName);
    }
    
    public function subscribeToTopic(topicName:String):void {
      if (!_initialized) {
        return;
      }
      // It will take 24 hours before you can see this topic on the Firebase console
      FCM.subscribeToTopic(topicName);
    }
    
    private function onTokenRefresh(e:FcmEvents):void {
      Debug.log("onTokenRefresh = " + e.token);
      if (onTokenRefreshCallback) {
        onTokenRefreshCallback(e);
        onTokenRefreshCallback = null;
      }
    }
    
    private function onMessage(e:FcmEvents):void {
      Debug.log(e.msg);
      var payload:Object = FCM.parsePayloadFromString(e.msg);
      
      if (payload) {
        for (var name:String in payload) {
          Debug.log(name + " = " + payload[name]);
        }
      }
      
      if (onMessageCallback) {
        onMessageCallback(e);
        onMessageCallback = null;
      }
      
    }
    
  }
}
```

log:
```
[trace] [LOG] 14:40:16 >> MobilePushExtended::checkGoogleAvailability result = SUCCESS
[trace] [LOG] 14:40:16 >> FCM Token is null
[trace] [LOG] 14:40:19 >> onTokenRefresh = ceOxFrFosdc:APA91bHNMXYecksomc8ZZpFdzj-H8WJIQ6oLbYR_L_wVrs3TSG7aHl4guDtRVt5Ei1TzZzBJ59LQAZF9yvUEiSdNzMuYOwbWgqsxnja_1A23Ebp4xdexoy5f9K7bbUkrSMh5NhlSH3Ll
```

In firebase console I create message for one device with right token.
Firebase says me that message status completed, but no push message displayed on device regardless app status (not started, foreground, background).

**Comment by myflashlab** [comment] 2018-06-13 04:48
Considering that that the Token is returned by the ANE and Firebase console uses the token with no error, means everything is setup correctly. Have you tried sending data messages also? data messages will not cause a notification but will be delivered to the app silently. check this post here; https://www.myflashlabs.com/send-fcm-mobile-notification-computer/

Also try something else, watch out the iOS debug console and see if there's an error or something when you send the fcm from firebase console or your server or the postman software (as explained in the above link)?

**Comment by ikuprin** [comment] 2018-06-15 11:31
Anyway not works...

This is token from ane:
`[LOG] 11:54:44 >> onTokenRefresh = csOgP8vBN_I:APA91bEvFwglaqiFRRJ023cAG8bqGGTh41x8nOV7IGgAI3Zg3hJxTc1THl6TVKJCWS2Vx0phBC2THL8_1F9iAEPHLR94i25T5AN48j18ya7Ynf0u6X0IxNfRHftn1utU0NrVOx844jqk`

Postman request:
```
{
  "notification": 
  {
    "title": "Title",
    "text": "Text",
    "sound": "default",
    "badge": "8",
    
    "color": "#FF9900",
    
    "click_action": "MY_INTENT"
  },
  "data": 
  {
    "obj": 
    {
      "Variable1":"value1",
      "Variable2":"value2"
    }
  },
  "priority" : "high",
  "registration_ids" : ["csOgP8vBN_I:APA91bEvFwglaqiFRRJ023cAG8bqGGTh41x8nOV7IGgAI3Zg3hJxTc1THl6TVKJCWS2Vx0phBC2THL8_1F9iAEPHLR94i25T5AN48j18ya7Ynf0u6X0IxNfRHftn1utU0NrVOx844jqk"]
}
```

FCM response:
```
{
    "multicast_id": 6991546910758822238,
    "success": 1,
    "failure": 0,
    "canonical_ids": 0,
    "results": [
        {
            "message_id": "0:1529053120723245%a1cf6413a1cf6413"
        }
    ]
}
```

No message on device..

If in request:
"to" : "/topics/news" instead id, response is:
```
{
    "message_id": 6868986670725341228
}
```
But message not displayed.

You are saying about iOS debug console... Can't find anything about push message, Can you show example what I need to find in log?

**Comment by myflashlab** [comment] 2018-06-16 05:56
The first time you ran your iOS app, did it ask for push notification permission? and did you accept it?

**Comment by ikuprin** [comment] 2018-06-18 09:56
Yes.

**Comment by myflashlab** [comment] 2018-06-18 12:41
I'm honestly out of ideas! On our side, everything is working fine and many/many other devs are also using it with no problem. 

As it seems, the token is generated correctly because the FCM server shows a successful respond. So, you need to look in the app side to see why it's not being received. If I were you at this stage, I would have done the following:

1. Considering that ```data``` FCM messages are using direct connections and won't create a notification, I would open up my app and send a ```data``` FCM first and see if I can receive it in my app.
2. I would first **uninstall** the app from my device and then create an empty app with the same bundle ID as my main app so I don't have to re-create Firebase and iOS certificates and provisions and in this test app I would add the Core and the FCM ANE and test it again to see what happens.

**Comment by LeapingSwan** [comment] 2018-06-18 12:48
Ok, I am already using a basic test app to do all this until I have it working.  I'll run through your suggestions and see what happens.  I'll get back to you.

Thanks

Stephen

**Comment by LeapingSwan** [comment] 2018-06-18 12:49
Sorry replied on the wrong thread!

**Comment by thatkidrich** [comment] 2018-07-05 19:47
I think I am having a similar problem. I set up an app using the code provided and It seems to be receiving the notification from inside my app, but I am not getting a Push notification or badge at all. Any ideas? I checked my  Decrypter file and I don't have <key>FirebaseAppDelegateProxyEnabled</key>
<false/> in it. Any ideas?

**Comment by myflashlab** [comment] 2018-07-06 05:58
@thatkidrich This is by design. The actual notification will be shown if the app is closed or in background. When app is running, you will receive the FCM message through listeners.

I'm closing the ticket as the initial problem is already answered/solved.

**Closed by myflashlab** 2018-07-06 05:58 UTC
Labels: FCM ANE
