### ISSUE TITLE
Core - FirebaseCore.ane initializes successfully, but not seeing any events in Firebase Dashboard for Android. Works for iOS.

### ISSUE THREAD

**Issue by HerbinCommando** [myflashlab/Firebase-ANE#111] opened 2017-05-03 18:30 UTC
I'm trying to integrate FirebaseCore.ane into our Air project. It looks like the ANE is integrated correctly, but I do not see any events on our Android app in the Firebase dashboard.
iOS is working, and i do see events in our iOS app in the Firebase dashboard.

When running on Android, I get a successful return from Firebase.init(). I also get some output in logcat saying Firebase has been initialized...

05-03 10:11:44.359 13578 13578 D FirebaseApp: com.google.firebase.auth.FirebaseAuth is not linked. Skipping initialization.
05-03 10:11:44.373 13578 13578 D FirebaseApp: com.google.firebase.crash.FirebaseCrash is not linked. Skipping initialization.
05-03 10:11:44.373 13578 13578 D FirebaseApp: com.google.android.gms.measurement.AppMeasurement is not linked. Skipping initialization.
05-03 10:11:44.373 13578 13578 I FirebaseInitProvider: FirebaseApp initialization successful

05-03 10:11:47.139 13578 13578 D FirebaseCore: AirCommand|||command:initFirebase
05-03 10:11:47.139 13578 13578 D FirebaseCore: AirCommand|||initFirebase > passed the initial initialization
05-03 10:11:47.139 13578 13578 D FirebaseCore: AirCommand|||initFirebase > initialization completed

**Comment by myflashlab** [comment] 2017-05-14 06:43
It seems like this is caused by the original Firebase SDK and it's not the ANE problem. We will investigate this more and contact the Firebase team when we have more information... Thanks for reporting this.

**Comment by myflashlab** [comment] 2017-07-22 13:54
This seems fixed in firebase ANE V5.0.0, if anything, let us know.

**Closed by myflashlab** 2017-07-22 13:54 UTC
Labels: Analytics ANE, Investigating, Waiting on Firebase team
