### ISSUE TITLE
The Authentication persists even after the user was deleted via Firebase console

### ISSUE THREAD

**Issue by GV3** [myflashlab/Firebase-ANE#12] opened 2016-08-30 06:43 UTC
Hi guys, 

I don't know if this is ANE-related or SDK related so I'll just post it here for you to test it on your own.

First is important to outline that the Firebase authentication session is persisted on the user's device in the iOS keychain. The keychain data for the application is not removed when the application is uninstalled. This information might be useful (I would also consider adding it to the wiki ;) )

Now, to reproduce the bug:

- Register a user via client using the email and password
- Sign in with the user 
- Close the App
- Go to the firebase console and DELETE the user 
- Open the App and notice how FirebaseUser.isAvailable == true

Best,

GV

PS: Could you consider giving backers and club members the possibility to remove the "Beta ANE" Notification? :)

PS2: The last update to the roadmap was 24 days ago, please tell me that you just forgot to update the roadmap.

**Comment by myflashlab** [comment] 2016-08-31 06:49
http://stackoverflow.com/questions/33784421/deletion-of-user-in-firebase-does-not-trigger-onauth-method explains why the user is still logged in even after being deleted. This is by design and can be fixed by either setting the rules or setting the session expiration interval in the Firebase Dashboard. this link may also be helpful to you: http://stackoverflow.com/questions/35960546/firebase-still-retrieving-authdata-after-deletion

> The last update to the roadmap was 24 days ago, please tell me that you just forgot to update the roadmap.

We haven't forgotten. It's just that we have been too busy! Firebase is a new SDK and if you check the Google changelogs, you will see that they are releasing new versions one after the other and this is troubling us and makes confusions. To avoid future confusion on the team, we decided to make some drastic changes to how we have setup the frameworks for the ANE development. That's the reason that we were not able to update the roadmap thing. Anyway, we are trying our best to finish the whole thing as planned in October and we are sure we can make it by that time :)

> Could you consider giving backers and club members the possibility to remove the "Beta ANE" Notification? :)

I'm afraid we have to wait for the final collection to be ready before that.

**Comment by GV3** [comment] 2016-08-31 11:40
Thank you for the link! All is clearer now.

> We haven't forgotten. It's just that we have been too busy!

Understood!

> > Could you consider giving backers and club members the possibility to remove the "Beta ANE" Notification? :)

> I'm afraid we have to wait for the final collection to be ready before that.

I would kindly ask you to reconsider two things about this:

1 - We are using two of your ANE, and I see two notifications popping one after the other. I presume the more ANEs we add; the more Notifications will appear. Would it make more sense to have only one for the core?

2 - This is the MOST IMPORTANT. The App we are building is also in Beta, and we have a board, potential partners, and testers who would like to test the App on their phones. Is the reason of this notifications to discourage developers using the ANE in production, or is it mainly an advert for the ANE?

If it were the first, I believe any serious dev understands that launching with an ANE in Beta is a risk. We, for example, won't take that chance. If it were the latter, I'm sure that beta testers and investors of the club members and backers of the ANE are not your target.

An idea: You could display the notification if the `aps-environment` is seto to `production` instead of `development` or similar?
```
<key>aps-environment</key>
<string>development</string>  <!-- No Notification -->
 <!-- <string>production</string> -->  <!-- BIG FAT Notification -->
```

Thank you in advance for considering this, I would very much appreciate it.

**Closed** 2016-09-13 11:55 UTC
