### ISSUE TITLE
(DB) DBServerValue.TIMESTAMP not save as timestamp (v.2.0 - Android)

### ISSUE THREAD

**Issue by majidatidrai** [myflashlab/Firebase-ANE#65] opened 2016-12-18 10:54 UTC
Since I updated into Firebase version 2.0, DBServerValue.TIMESTAMP is being saved as "DBServerValue_TIMESTAMP" instead of current server timestamp.

**Comment by myflashlab** [comment] 2016-12-19 12:09
Would you post the block of your AS code where you are saving the timestamp?

**Comment by myflashlab** [comment] 2016-12-19 13:03
We are not able to duplicate this. It's working just fine! please try to provide more information on this.

**Comment by majidatidrai** [comment] 2016-12-19 17:58
Just simple like this:

```
var dataObject:Object = new Object();
dataObject.name = "Blah blah";
dataObject.created_time = DBServerValue.TIMESTAMP;
dataObject.updated_time = DBServerValue.TIMESTAMP;
				
trace("[FIRE] setValueObject -> " + JSON.stringify(dataObject));
				
var ref: DBReference = DB.getReference(path);
ref.addEventListener(DBEvents.SET_VALUE_SUCCESS, onUpdateSuccess);
ref.addEventListener(DBEvents.SET_VALUE_FAILURE, onUpdateFailure);
ref.setValue(dataObject);
```

It worked fine with v.1.2.0, only happen when I upgraded to v.2.0.0

Maybe I missed something... hmm..

**Comment by myflashlab** [comment] 2016-12-22 11:57
It is normal to see the String value when tracing a stringified object like ```trace("[FIRE] setValueObject -> " + JSON.stringify(dataObject));```

The String will be changed to the server timestamp on the server side not the client side. So, ignore what you are seeing on the trace method and instead see the values changing on the database. It should work fine because we have tested that twice!

**Comment by mrgoonie** [comment] 2016-12-22 17:03
Just asking, which ANE contains DBServerValue.TIMESTAMP? Is it "firebase_database.ane" or "firebaseDatabase.ane" or "firebase_databaseConnection.ane" ?

**Comment by myflashlab** [comment] 2016-12-26 10:32
@mrgoonie  ```firebaseCore.ane``` is the one which contains AS API. the other two are just dependency ANEs required for the Android side. Detailed information can be found here: https://github.com/myflashlab/Firebase-ANE/blob/master/Dependencies.md

**Comment by myflashlab** [comment] 2017-02-07 07:43
I can confirm that V3 on the Android side is saving timestamp incorrectly. We will be releasing a new version soon. We're working on it. as soon as it's fixed, we'll let you know.

**Comment by mrgoonie** [comment] 2017-02-07 07:53
Yea, because you guys only test it twice, please test it triple next time! 😃

**Comment by myflashlab** [comment] 2017-02-24 12:46
Ok, this problem is now fixed and we are releasing Firebase V4 soon with a lot of new features and bug fixes including this one. Thanks for reporting.

**Closed by myflashlab** 2017-02-24 12:46 UTC
Labels: DB ANE

**Comment by mrgoonie** [comment] 2017-02-27 08:48
Thanks @myflashlab, any changes there is a new release in this week? Sorry for pushing, but my client start being out of patience.

**Comment by myflashlab** [comment] 2017-03-06 06:09
We are adding the final touches. It should be uploaded today to tomorrow!
